Add The Readme file for Anuket-Documentation Repository
anuket-project/anuket-documentation pull request #13
Opened 2024-06-24 18:04 UTC by Aryan-Singla

Add The Readme file for the Anuket-Documentation Repository describes what the repository is all about

2024-06-25 05:38 UTC, CsatariGergely requested changes

2024-06-25 05:38 UTC, CsatariGergely commented on Readme.md
> +### Install Sphinx
Sphinx and all other dependencies will be installed by tox. 

Here we should install only tox with `pip install tox`

2024-06-25 05:38 UTC, CsatariGergely commented on Readme.md
> +## Navigate to the Documentation Directory
This is not needed

2024-06-25 05:38 UTC, CsatariGergely commented on Readme.md
> +python -m sphinx -b html . _build/html
Building should be done with `tox -e docs`

2024-06-25 09:11 UTC, Aryan-Singla commented
Hi @CsatariGergely 
I have add your suggestions Please check

2024-07-03 14:34 UTC, CsatariGergely approved these changes

2024-07-03 14:35 UTC, merged